export const SPECIALIZATIONS: Record<string, string> = {
  CARD: 'Cardiologist',
  DERM: 'Dermatology',
  IMMONCO: 'Immunodermatology and Oncodermatology',
  GPHY: 'General Physician',
  GP: 'General Practitioner',
  GS: 'General Surgery',
  IM: 'Internal Medicine',
  CARDADULT: 'Adult Cardiologist',
  HEMA: 'Hematology',
  IMID: 'Infectious Disease',
  PULMO: 'Pulmonology',
  MEDSPEC: 'Medical Specialist',
  NEURO: 'Neurology',
  OBGYN: 'Obstetrician-Gynecologist',
  OPTH: 'Ophthalmology',
  ENT: 'Otorhinolaryngology - Head & Neck Surgery',
  PEDIA: 'Pediatrics',
  PHYTHERA: 'Physical Therapist',
  PSYCH: 'Psychiatry',
  PSYCHO: 'Psychology',
  REHAB: 'Rehabilitation Medicine',
  URO: 'Urology',
};
