export const doctorSpecializations = [
  { code: "CARD", name: "Cardiologist" },
  { code: "DERM", name: "Dermatology" },
  { code: "IMMONCO", name: "Immunodermatology and Oncodermatology" },
  { code: "GPHY", name: "General Physician" },
  { code: "GP", name: "General Practitioner" },
  { code: "GS", name: "General Surgery" },
  { code: "IM", name: "Internal Medicine" },
  { code: "CARDADULT", name: "Adult Cardiologist" },
  { code: "HEMA", name: "Hematology" },
  { code: "IMID", name: "Infectious Disease" },
  { code: "PULMO", name: "Pulmonology" },
  { code: "MEDSPEC", name: "Medical Specialist" },
  { code: "NEURO", name: "Neurology" },
  { code: "OBGYN", name: "Obstetrician-Gynecologist" },
  { code: "OPTH", name: "Ophthalmology" },
  { code: "ENT", name: "Otorhinolaryngology - Head & Neck Surgery" },
  { code: "PEDIA", name: "Pediatrics" },
  { code: "PHYTHERA", name: "Physical Therapist" },
  { code: "PSYCH", name: "Psychiatry" },
  { code: "PSYCHO", name: "Psychology" },
  { code: "REHAB", name: "Rehabilitation Medicine" },
  { code: "URO", name: "Urology" },
] as const;
